//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIPresentacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIPresentacion.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rent.
        /// </summary>
        internal static string btnAlquilar {
            get {
                return ResourceManager.GetString("btnAlquilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string btnAlta {
            get {
                return ResourceManager.GetString("btnAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string btnBaja {
            get {
                return ResourceManager.GetString("btnBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate amount.
        /// </summary>
        internal static string btnCalcularImporte {
            get {
                return ResourceManager.GetString("btnCalcularImporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load.
        /// </summary>
        internal static string btnCargar {
            get {
                return ResourceManager.GetString("btnCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string btnEntrar {
            get {
                return ResourceManager.GetString("btnEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record.
        /// </summary>
        internal static string btnGrabar {
            get {
                return ResourceManager.GetString("btnGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean.
        /// </summary>
        internal static string btnLimpiar {
            get {
                return ResourceManager.GetString("btnLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Most Rented Vehicles.
        /// </summary>
        internal static string btnMasRentados {
            get {
                return ResourceManager.GetString("btnMasRentados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Less Rented Vehicles.
        /// </summary>
        internal static string btnMenosRentados {
            get {
                return ResourceManager.GetString("btnMenosRentados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modification.
        /// </summary>
        internal static string btnModificacion {
            get {
                return ResourceManager.GetString("btnModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname.
        /// </summary>
        internal static string lblApellido {
            get {
                return ResourceManager.GetString("lblApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Client.
        /// </summary>
        internal static string lblCliente {
            get {
                return ResourceManager.GetString("lblCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string lblContraseña {
            get {
                return ResourceManager.GetString("lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Days.
        /// </summary>
        internal static string lblDias {
            get {
                return ResourceManager.GetString("lblDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NID.
        /// </summary>
        internal static string lblDNI {
            get {
                return ResourceManager.GetString("lblDNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birthdate.
        /// </summary>
        internal static string lblFechaNac {
            get {
                return ResourceManager.GetString("lblFechaNac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string lblID {
            get {
                return ResourceManager.GetString("lblID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        internal static string lblImporte {
            get {
                return ResourceManager.GetString("lblImporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brand.
        /// </summary>
        internal static string lblMarca {
            get {
                return ResourceManager.GetString("lblMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Model.
        /// </summary>
        internal static string lblModelo {
            get {
                return ResourceManager.GetString("lblModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patent.
        /// </summary>
        internal static string lblPatente {
            get {
                return ResourceManager.GetString("lblPatente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string lblTipo {
            get {
                return ResourceManager.GetString("lblTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicles.
        /// </summary>
        internal static string lblVehiculos {
            get {
                return ResourceManager.GetString("lblVehiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        internal static string radioButton1 {
            get {
                return ResourceManager.GetString("radioButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string radioButton2 {
            get {
                return ResourceManager.GetString("radioButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        internal static string radioEspañol {
            get {
                return ResourceManager.GetString("radioEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string radioIngles {
            get {
                return ResourceManager.GetString("radioIngles", resourceCulture);
            }
        }
    }
}
